import type { Metadata } from "next";
import "./globals.css";
import AppHeader from "./_components/layout/AppHeader";
import AppFooter from "./_components/layout/AppFooter";
import CartProvider from "./_context/CartContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <CartProvider>
                    <AppHeader />
                    <main className="min-h-[calc(100vh-60px)]">{children}</main>
                    <AppFooter />
                </CartProvider>
            </body>
        </html>
    );
}
