import type { Metadata } from "next";
import "./globals.css";
import AppHeader from "./_components/layout/AppHeader";
import AppFooter from "./_components/layout/AppFooter";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="min-h-full flex flex-col">
                <AppHeader />
                <main>{children}</main>
                <AppFooter />
            </body>
        </html>
    );
}
